version: '3.6'
networks:
  backend:

services:
  auth-service-test:
    networks:
      - backend
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "lein run migrate && lein test-refresh && lein run" 
    ports:
      - "3006:3000"
    depends_on:
      - db-test
    links:
      - db-test
    env_file:
      - .test-env
    volumes:
      - ./:/app

  db-test:
    networks:
      - backend
    image: postgres
    env_file:
      - .test-env
    ports:
      - "5555:5432"
    volumes:
      - ../data:/var/lib/postgresql/data-test
