version: '3.6'
networks:
  backend:

services:
  auth-service:
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "java -jar target/uberjar/<app>.jar migrate && java -jar /auth-service/app.jar"
    ports:
      - "3005:3000"
    depends_on:
      - db
    env_file:
      - .lein-env

  db:
    networks:
      - backend
    image: postgres
    env_file:
      - .lein-env
    volumes:
      - ../data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
