version: '3.6'
networks:
  backend:

services:
  auth-service:
    networks:
      - backend
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: lein run 
    ports:
      - "3005:3000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

  db:
    networks:
      - backend
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ../data:/var/lib/postgresql/data
